[[log-notifier]]
= Log Notifier

The log notifier is the only notifier that is enabled by default when
the notification service is activated.

The default output for the log notifier is the configured instance log
file, which is either the _server.log_ file or _cluster.log_ file, depending
on the instance configuration.

The log notifier only handles the output of notifications from the
notification service sent to the log and is not responsible for any
other log output - more details on Payara Server logging can be found on
link:documentation/core-documentation/logging/logging.adoc[the logging page].

[[configuration]]
== Configuration

By default, the log notifier will receive notifications from the notification
service and output them to the configured logs when activated.

[[payara-configuration]]
=== Payara Configuration

The log notifier is, by default, disabled on new domains.

To explicitly enable the log notifier, run the following command:

[source, shell]
----
asadmin notification-log-configure --enabled=true --dynamic=true
----

More details on specific commands for the notification service can be
found on the link:/documentation/extended-documentation/notification-service/notification-service.adoc[notification service page].

[[log-configuration]]
=== Log Configuration

To get the current configuration of the log notifier, run the following command:

[source, shell]
----
asadmin get-log-notifier-configuration
----

It will return the details of the current log notifier configuration, like in
the following example:

[source, shell]
----
Enabled
true
----
