= Payara Community Edition Documentation Repository

WARNING: **This repository is no longer used to generate the Documentation for the Payara Platform Community edition and has been replaced by the link:https://github.com/payara/Payara-Documentation[unified documentation repository]. This repository is kept for legacy purposes, as its used to generate the documentation for legacy releases equal to or older than 5.2022.1**

Official technical documentation repository of the Payara Platform Community Edition which is maintained by members of the Payara organization. All documentation material is written in Asciidoctor format.

This documentation repository is structured in conformance to **Antora version 2.3.0** format: https://docs.antora.org/antora/2.3/. This repository is used to generate all the HTML pages that are published at https://docs.payara.fish/community/ as configured in the https://github.com/payara/payara-documentation-playbook[Payara Documentation's Antora Configuration Repository]

== Branches

All branches of this repository represent a different version of the Payara Platform's Community Stream releases. In particular the following branches:

* 4.1.2.174
* 4.1.2.173
* 4.1.2.172
* 4.1.1.171
* 4.1.1.164
* 4.1.1.163
* 4.1.1.162
* 4.1.1.161.1
* 4.1.1.161
* 4.1.1.154
* 4.1.1.153
* 4.1.1.152.1
* 4.1.1.152
* 4.1.1.151
* 4.1.1.144

Correspond to older releases of the Payara Platform's 4.1.x documentation and as such are not publicly available at the main site. Due to this, the file structure of these branches does not conform to the Antora layout.
