
[[how-to-use-variable-references]]
= How to use variable references

Variable references can be used inside text values in the following configuration files:

*   domain.xml (inside attribute values or inside text nodes that contain a configuration value)
*   logging.properties (inside property values)

Variable references can be used inside text values also in the following places within a deployed package (_Since Payara Server 4.1.1.172_):

* Package descriptors:
**   web.xml / glassfish-web.xml
**   ejb-jar.xml / glassfish-ejb-jar.xml
**   application.xml / glassfish-application.xml
**   glassfish-resources.xml
* Framework descriptors:
**   persistence.xml
**   faces-config.xml
* In the annotations `@EJB`, `@WebService`, `@Stateless`, `@Stateful`, `@Singleton`, `@ActivationConfigProperty`, `@DataSource`, `@WebServlet`
*   In JNDI lookups inside an application

Multiple references to system properties and environment variables can be used within the same configuration value, concatenating any number of variable references and plain text chunks. When a reference to a password alias is used, it has to expand to whole value of a property and cannot be combined with any other text or variable reference.

[[examples]]
== Examples

An example of variable references within an annotation:

[source,java]
----
@DataSourceDefinition(name="java:global/ExampleDataSource",
      className="com.mysql.jdbc.jdbc2.optional.MysqlXADataSource",
      user="${mysql.user}",
      password="${ALIAS=mysql-db-password}",
      databaseName="mysql",
      serverName="localhost"
   )
----

An example of variable references within a `web.xml` descriptor

[source,xml]
----
<data-source>
     <name>java:global/ExampleDataSource</name>
     <class-name>com.mysql.jdbc.jdbc2.optional.MysqlXADataSource</class-name>
     <server-name>localhost</server-name>
     <port-number>3306</port-number>
     <database-name>mysql</database-name>
     <user>${mysql.user}</user>
     <password>${ALIAS=mysql-db-password}</password>
</data-source>
----

An example of multiple variable references combined in a single value withing the `domain.xml`:

[source,xml]
----
<domain log-root="${com.sun.aas.instanceRoot}/${ENV=STAGE_NAME}/logs">
----