[[eclipse-microprofile-opentracing]]
= Eclipse MicroProfile OpenTracing

_Since Payara Server 4.1.2.182 and 5.182_

Provided version of the API: {{ book.mpOpenTracingSpecUrl }}[MicroProfile Open Tracing {{ book.mpOpenTracingVersion }}]

[[background]]
== Background

The Open Tracing API was created to allow easier tracing of the flow of a request in microservices environment across service boundaries.

A full overview for the reasoning behind the API can be found in https://github.com/eclipse/microprofile-opentracing/blob/master/README.adoc[the README of the MicroProfile OpenTracing source code repository].

{{ book.mpOpenTracingSpecUrl }}[The complete specification] is maintained in the same repository.

[[text-and-binary-carriers]]
== Text and Binary Carriers Support

_Since Payara Platform 4.1.2.183 and 5.183_

The Payara Platform implementation of the `io.opentracing.Tracer` interface supports the following carriers:

* `TextMap` carriers with `HTTP_HEADERS` and `TEXT_MAP` formats 
* `ByteBuffer` carriers that use the `BINARY` format

[[jax-ws-support]]
== JAX-WS Support

_Since Payara Server 5.192_

The Payara Platform's MicroProfile implementation supports tracing of requests that are handled by SOAP Web Services implemented via the JAX-WS API. Since JAX-WS is only supported on Payara Server Full Profile, this support is not covered on Payara Micro.

[[opentracing-configuration]]
=== OpenTracing Configuration

You can configure the notifiers and open tracing service by using the link:/documentation/payara-server/request-tracing-service/asadmin-commands.adoc[asadmin commands] and also using the link:/documentation/payara-server/request-tracing-service/configuration.adoc[Administration console].

[[alternative-implementation]]
== Using Alternate Opentracing Implementations

_Since Payara Server 5.194_

If you wish to use an alternative implementation of OpenTracing, i.e. Jaeger, then the alternative implementation must be proved as a jar in the lib directory of your domain. In it must be a file named io.opentracing.Tracer under META-INF/services, with the name of the class implementing io.opentracing.Tracer. That implmentation must have a no-argument constructor. This will trace all JAX-RS and JAX-WS requests but not servlet or JSF requests. Payara's request tracing service MUST also be enabled. All other configuration within Payara's request tracing service will have no effect on the supplied tracer, which must be self-configured.
