= Eclipse MicroProfile


== What is Eclipse MicroProfile?
The MicroProfile project was launched in June 2016 as a collaborative effort
between Java application server vendors and the enterprise Java community to 
enable fast innovation.

MicroProfile is a specification which provides a set of APIs focused on 
microservices. The complete MicroProfile API is provided as a Bill Of Materials
(BOM) which can be used by developers as a generic dependency provided by a
vendor of their choice.

Payara has been part of the MicroProfile project from its inception and,
therefore, supports all specifications of MicroProfile.


== What does each specification contain?
[cols=",a,a", options="header"]
|===
|Version
|Specifications
|Maven

| 1.3
|
* JAX-RS 2.0
* CDI 1.2
* JSON-P 1.0
* https://github.com/eclipse/microprofile-config/releases/tag/1.2[Config 1.2]
* https://github.com/eclipse/microprofile-metrics/releases/tag/1.1[Metrics 1.1]
* https://github.com/eclipse/microprofile-health/releases/tag/1.0[Health Check 1.0]
* https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/1.0[Fault Tolerance 1.0]
* https://github.com/eclipse/microprofile-jwt-auth/releases/tag/1.0[JWT Authentication 1.0]
* https://github.com/eclipse/microprofile-opentracing/releases/tag/1.0[OpenTracing 1.0]
* https://github.com/eclipse/microprofile-open-api/releases/tag/1.0[OpenAPI 1.0]
* https://github.com/eclipse/microprofile-rest-client/releases/tag/1.1[Rest Client 1.1]


| [source, xml]
----
<dependency>
    <groupId>org.eclipse.microprofile</groupId>
    <artifactId>microprofile</artifactId>
    <version>1.3</version>
    <type>pom</type>
    <scope>provided</scope>
</dependency>
----


| 1.2
|
* JAX-RS 2.0
* CDI 1.2
* JSON-P 1.0
* https://github.com/eclipse/microprofile-config/releases/tag/1.1[Config 1.1]
* https://github.com/eclipse/microprofile-metrics/releases/tag/1.0[Metrics 1.0]
* https://github.com/eclipse/microprofile-health/releases/tag/1.0[Health Check 1.0]
* https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/1.0[Fault Tolerance 1.0]
* https://github.com/eclipse/microprofile-jwt-auth/releases/tag/1.0[JWT Authentication 1.0]


| [source, xml]
----
<dependency>
    <groupId>org.eclipse.microprofile</groupId>
    <artifactId>microprofile</artifactId>
    <version>1.2</version>
    <type>pom</type>
    <scope>provided</scope>
</dependency>
----


| 1.1
|
* JAX-RS 2.0
* CDI 1.1
* JSON-P 1.0
* http://microprofile.io/project/eclipse/microprofile-config[Config 1.0]

| [source, xml]
----
<dependency>
    <groupId>org.eclipse.microprofile</groupId>
    <artifactId>microprofile-bom</artifactId>
    <version>1.1.0</version>
    <type>pom</type>
    <scope>provided</scope>
</dependency>
----

| 1.0
| 
* JAX-RS 2.0
* CDI 1.1
* JSON-P 1.0

| [source, xml]
----
<dependency>
    <groupId>io.microprofile</groupId>
    <artifactId>microprofile</artifactId>
    <version>1.0.0</version>
    <type>pom</type>
    <scope>provided</scope>
</dependency>
----

|===

== Payara Support for MicroProfile

Version1.3::
Version 1.3 of MicroProfile includes 3 new APIs, and updates to the existing Metrics and Config APIs. 
This is supported by both Payara Server and Payara Micro from release *4.1.2.182* and *5.182*
Version 1.2::
Version 1.2 of MicroProfile includes 4 new APIs and an update to the existing config API and is 
supported by both Payara Server and Payara Micro from release *4.1.2.181* and *5.181*
Version 1.1::
Version 1.1 of the MicroProfile specification includes the Config 1.0 API and is
supported by both Payara Server and Payara Micro from release *4.1.2.173*
Version 1.0::
Since version 1.0 of MicroProfile only included existing specifications already
supported by Payara Server and Payara Micro, an application targeting version
1.0 of MicroProfile can be run on any release of Payara Server or Payara Micro.
