[[rest-client-api]]
= Eclipse MicroProfile Rest Client API

:repo: https://github.com/eclipse/microprofile-rest-client/tree/1.3.4

_Since Payara Server 4.1.2.182 and 5.182_

Provided version of the API: {{ book.mpRestClientSpecUrl }}[MicroProfile Rest Client {{ book.mpRestClientVersion }}]

[[background]]
== Background

The MicroProfile Rest Client provides a type-safe approach to invoke RESTful services over HTTP.
An aim of this specification is to provide a much more natural coding style, with the underlying MicroProfile implementation handling the communication between the client and service.

The {repo}[Eclipse MicroProfile Rest Client] repository contains a number of {repo}/spec/src/main/asciidoc/clientexamples.asciidoc[examples] and information about how to use this API.

[[cdi]]
== CDI
Full MicroProfile documentation available {repo}/spec/src/main/asciidoc/cdi.asciidoc[here]

Rest Client interfaces may be injected as CDI beans.
To do this, you must first register your interface class by using the `@RegisterRestClient` annotation, and then use the `@RestClient` qualifier on the injected bean, like so:

[source, java]
----
@RegisterRestClient
public interface MyServiceClient {
    @GET
    @Path("/greet")
    Response greet();
}

@ApplicationScoped
public class MyService {
    @Inject
    @RestClient
    private MyServiceClient client;
}
----

[[async]]
== Async

Full MicroProfile documentation available {repo}/spec/src/main/asciidoc/async.asciidoc[here]

It is possible for Rest Client interface methods to be declared asynchronous.
This allows the thread invoking the interface method to proceed while the RESTful request occurs on another thread.

Any method of the interface class is deemed an asynchonronous method if it has a return type of `CompletionStage`.

[[providers]]
== Providers

Full MicroProfile documentation available {repo}/spec/src/main/asciidoc/providers.asciidoc[here]

The `RestClientBuilder` interface extends the `Configurable` interface from JAX-RS, allowing a user to register custom providers while it's being built.
Payara Server and Micro support the following provider types:

* `ClientRequestFilter`
* `ClientResponseFilter`
* `MessageBodyReader`
* `MessageBodyWriter`
* `ParamConverter`
* `ReaderInterceptor`
* `WriterInterceptor`
* `ResponseExceptionMapper`

See the full {repo}/spec/src/main/asciidoc/providers.asciidoc[MicroProfile documentation] for the registration methods.
