= Configuring Payara Fang

Payara Fang is configurable through asadmin commands. This feature is in
technical preview, so some things may not work quite as intended.

== Setting Payara Fang Configuration
The `set-payara-fang-configuration` asadmin command is used to configure
Payara Fang. This command requires the server to be running. Each configuration
property can be configured individually or all together.


=== Enabled

[source, shell]
----
asadmin> set-payara-fang-configuration --enabled=true
----
By default, Payara Fang is disabled.


=== Target

[source, shell]
----
asadmin> set-payara-fang-configuration --enabled=true --target=${Target}
----
If no target is specified, the command will enable Payara Fang on the
domain configuration _(server-config)_. The `--target` option enables
Payara Fang on another instance or cluster.


=== Context Root

[source, shell]
----
asadmin> set-payara-fang-configuration --contextroot=${ContextRoot}
----
The `contextroot` property defines which URLs the Payara Fang application uses.
The context root of the Payara Fang application defaults to `/fang`, but can
be specified with the `--contextroot` option.


=== Name

[source, shell]
----
asadmin> set-payara-fang-configuration --name=${Name}
----
The `name` property defines the name of the deployed Payara Fang. This option
defaults to "Fang".


=== Security Enabled
[source, shell]
----
asadmin> set-payara-fang-configuration --securityenabled=true
----
The `securityenabled` property defines whether the Payara Fang application is
available over HTTPS. Since Payara Fang is hosted on the `admin-listener`,
this requires secure admin to be enabled.

Enabling secure admin can be done by first configuring the admin password with
the `change-admin-password` command, then using the `enable-secure-admin`
command. Enabling secure admin requires a server restart.

When `securityenabled` is set to true, a username and password is required to
use Payara Fang. By default the username and password is `fang`. The user is
defined in the `file` realm. The password can be changed with the
following command:
[source, shell]
----
asadmin> update-file-user --groups=fang --target=server-config --authrealmname=file fang
----
This updates the `fang` user, which is part of the `fang` group. Any users which
are able to login to Payara Fang must be defined in the `file` realm and be part
of the `fang` group. You can create a new user with:
[source, shell]
----
asadmin> create-file-user --groups=fang --target=server-config --authrealmname=file whatever
----


== Getting Payara Fang Configuration
The `get-payara-fang-configuration` asadmin command is used to get the
configuration of Payara Fang. This command requires the server to be running.
