= Using Payara Fang

Payara Fang uses a similar API to Jolokia, but with a subset of the features.
The REST API is hosted on `${base-url}/${Fang-Context-Root}/rest`, so with default settings
it is hosted at `localhost:4848/fang/rest`.


== Operations

====
Payara Fang supports a subset of operations defined in the Jolokia API. It will
expand to include more, but in technical preview currently only supports the
`read` operation.
====

=== Read

The `read` operation reads the details of the MBean requested. It accepts the
following format:

[source, bash]
----
${base-url}>/read/${mbean-name}/${attribute-name}
----
So for example, if you want the MBean `java.lang:type=Memory`, you might make a
GET request to: `http://localhost:4848/fang/rest/read/java.lang:type=Memory`.
A sample output is shown below:
[source]
----
{
  "request": {
    "mbean": "java.lang:type=Memory",
    "type": "read"
  },
  "value": {
    "HeapMemoryUsage": {
      "committed": 450363392,
      "init": 264241152,
      "max": 477626368,
      "used": 97480984
    },
    "ObjectPendingFinalizationCount": 0,
    "NonHeapMemoryUsage": {
      "committed": 139460608,
      "init": 2555904,
      "max": -1,
      "used": 122389432
    },
    "Verbose": false,
    "ObjectName": "java.lang:type=Memory"
  },
  "timestamp": 1502799650273,
  "status": 200
}
----
A couple of quick notes:

* The attribute name can be empty
* A list of attribute names can be found in the request of an empty attribute
name under `value`, So for the JSON returned from
`http://localhost:4848/fang/rest/read/java.lang:type=Memory`, `HeapMemoryUsage`
and `NonHeapMemoryUsage` are both attribute names.


=== Search

=== List

=== Write

=== Version

The `version` operation isn't supported explicitly, but a GET request on the
default operation produces similar results.
