= Yubikey Support

_Since versions 4.1.2.183 and 5.182_

The Payara API provides a way to authenticate with Yuibikey using the `@YubikeyIdentityStoreDefinition` annotation .This works in the same way as other identity stores in the Security API.

[[usage]]
== Usage

The Yubikey identity store is defined through the `@YubikeyIdentityStoreDefinition` annotation. Specifying this in a valid place as defined by the Security API will create the identity store. Often this may mean that any class is a valid position.

[[usage-example]]
=== Example


[source, java]
----
@YubikeyIdentityStoreDefinition(yubikeyAPIKey="qwertyuiop1234567890", yubikeyAPIClientID=98765)
public class ApplicationConfiguration {

}
----


[[configuration]]
== Configuration

The `@YubikeyIdentityStoreDefinition` annotation has several configuration options.
They are detailed below.

.Configuration Options
|===
| Option | Required | Description

| `yubikeyAPIClientID`
| false
| The client identifier used to identiy the application

| `yubikeyAPIKey`
| true
| The API key

| `priority`
| true
| The priority of the identity store
| N/A.

| `priorityExpression`
| true
| EL expression which overrides the priority value

| `yubikeyAPIClientIDExpression`
| false
| EL expression which overrides the yubikeyAPIClientID value
|===


[[links]]
== Links

To read more about Yubikey itself, visit https://www.yubico.com/.

