= Arquillian Containers

{% if book.currentVersion == "5.Beta2" %}

WARNING: This feature is released in *_technical preview_*. It's fully usable and supported but it's subject to change in future versions. Read more in link:/general-info/technical-preview.adoc[Features in Technical Preview].

{% endif %}

The Payara Arquillian containers provide various Arquillian containers for integration testing with Payara.

In version {{ book.currentVersion }}, there are containers available for the following distributions:

* link:payara-micro.adoc[Payara Micro]
* Payara Embedded (not yet documented)
* Payara Remote (not yet documented)
* Payara Managed (not yet documented)

=== Obtaining the Containers

Arquillian containers are included in a project via their Maven coordinates:

[source,XML]
----
<dependency>
    <groupId>fish.payara.arquillian</groupId>
    <artifactId>arquillian-payara-${container-name}</artifactId>
    <version>${version}</version>
</dependency>
----

Some containers will be either in development or an early release version. In these cases
the same process can be used, but the artifact will need to be built from source.
The containers can be found in the main Payara source.

Clone the link:https://github.com/payara/Payara[Payara] Git repository:

----
git clone https://github.com/payara/Payara.git
----

Build and install:

----
cd Payara/
mvn clean install -DskipTests
----