[[notification-service-command-reference]]
= Notification Service Command Reference

[[notification-configure]]
== `notification-configure`

*Usage*::
`asadmin> notification-configure --enabled=true --dynamic=true`

*Aim*::
Enables or disables the service.

[[command-options]]
=== Command Options

[cols=",,,,",options="header",]
|=======================================================================
|Option |Type |Description |Default |Mandatory
|`--enabled=true` |Boolean |Enables or disables the service |False |No
|`--dynamic=true` |Boolean |When set to true, applies the changes
without a restart. Otherwise a restart is required. |False |No
|=======================================================================

NOTE: The argument `--dynamic=true` is necessary to turn on the service for a
running server, otherwise the change would only be applied after a
server restart.

[[example]]
=== Example

[source, shell]
----
asadmin> notification-configure --enabled=true --dynamic=true
----

[[notifier-list-services]]
== `notifier-list-services`

*Usage*::
`asadmin> notifier-list-services`

*Aim*::
Lists available notifiers to use with the service. These can then
be configured individually or referenced by other service commands, for
example the
link:/documentation/extended-documentation/request-tracing-service/asadmin-commands.adoc#requesttracing-configure-notifier[`requesttracing-configure-notifier`]
command.

[[command-options-1]]
=== Command Options

There are no available options for this command.

[[example-1]]
=== Example

Running the command on release _4.1.1.164_ would yield the following results:

----
Available Notifier Services:
    service-log

Command notifier-list-services executed successfully.
----

[[notification-configure-notifier]]
== `notification-configure-notifier`

*Usage*::
`asadmin> notification-configure-notifier --notifierName=${name} --notifierEnabled=true --dynamic=true`

*Aim*::
Enables or disables an individual notifier for the notification service to use.

[[command-options-2]]
=== Command Options

[cols=",,,,",options="header",]
|=======================================================================
|Option |Type |Description |Default |Mandatory
|`--notifierName=${name}` |String |The name of the notifier to configure
|- |Yes
|`--notifierEnabled=true` |Boolean |Enables or disables the service
|False |No
|`--dynamic=true` |Boolean |When set to true, applies the changes
without a restart. Otherwise a restart is required. |False |No
|=======================================================================

[[example-2]]
=== Example:

[source, shell]
----
asadmin> notification-configure-notifier
  --notifierName=service-log
  --notifierEnabled=true
  --dynamic=true
----

[[get-notification-configuration]]
== `get-notification-configuration`

*Usage*::
`asadmin> get-notification-configuration`

*Aim*::
This command can be used to list the details of the Notification Service.

[[command-options-3]]
=== Command Options

There are no available options for this command.

[[example-3]]
=== Example

Running the command will give output similar to the following:

----
Enabled  Notifier Enabled  Notifier Name
false    false             service-log

Command get-notification-configuration executed successfully.
----

[[set-notification-configuration]]
== `set-notification-configuration`

*Usage*::
`asadmin> set-notification-configuration --enabled=true --dynamic=true --notifierName="service-log" --notifierEnabled=true --notifierDynamic=true`

*Aim*::
This command can be used to set all configuration of the
Notification Service at once.

[[command-options-4]]
=== Command Options

[cols=",,,,",options="header",]
|=======================================================================
|Option |Type |Description |Default |Mandatory
|`--enabled=true` |Boolean |Enables or disables the service |False |No
|`--dynamic=true` |Boolean |When set to true, applies the changes
without a restart. Otherwise a restart is required. |False |No
|`--notifierName` |String |The name of the notifier to use
|`service-log` |Yes
|`--notifierEnabled` |Boolean |Enables or disables notifications |false
|Yes
|`--notifierDynamic=true` |Boolean |When set to true, applies the
changes without a restart. Otherwise a restart is required. |false |No
|=======================================================================

[[example-4]]
=== Example

[source, shell]
----
asadmin> set-requesttracing-configuration
    --enabled=true
    --dynamic=true
    --notifierName="service-log"
    --notifierEnabled=true
    --notifierDynamic=true
----
