[[overview]]
= Overview

This section describes how to deal with known or unknown security issues and common vulnerabilities and exploits (CVEs) related to the Payara Platform

[[download-security-fixes]]
== Security Fixes

Reported security vulnerabilities will get patched as soon as possible and delivered in a future release. For this reason, it is recommended to always stay up to date with the current release.

[[locating-security-vulnerabilities]]
== Locating Security Vulnerabilities

In order to locate the release a security update has been included for a specific vulnerability, search in the xref:/security/security-fix-list.adoc[security fixes summary] page for the specific vulnerability using its https://cve.mitre.org/cve/identifiers/[CVE identifier].

For each of these security vulnerabilities, a reference to the _*Pull Requests*_ merged to fix them is given for auditing purposes. If a security vulnerability has been reported, but is not related or it doesn't affect the Payara Platform in any way, a proper justification will be detailed in its observation colum.

[[reporting-security-issues]]
== Reporting Security Issues

Payara Services Limited is very active at identifying and fixing possible security vulnerabilities included into Payara Server and Payara Micro that are either inherited from GlassFish upstream or introduced by new features developed.

To report a new security issue, please send an email with the described flaws and vulnerabilities to mailto:security@payara.fish[security@payara.fish].

IMPORTANT: Don't use this address to report bugs or other non-security issues as they will be ignored, https://github.com/payara/Payara/issues[raise a new] for raising a new issue detailing the problem at hand.

NOTE: All networked servers are subject to denial of service (_DoS_) attacks, and we cannot provide fixes to generic problems (such as a client streaming lots of data to your server, or re-requesting the same URL repeatedly). Instead, focus on security issues that can be targeted at specific topics like session hacking, XSS injection, CSRF attacks and so forth.

Lastly, you can also direct inquiries about reported CVE issues detected in similar Java platforms or application servers (like Apache Tomcat, JBoss WildFly, etc.) and let us research whether or not Payara Server is affected by such issues.