[[application-deployment]]
= Application Deployment

Applications can be deployed to Payara Server in the same way as 
_GlassFish Server 4.1 Open Source Edition_. Payara Server does not modify
this process but does add some new features to deployment descriptor files
which are documented in the following pages.

== Deploying On Server Start
GlassFish has had the ability to deploy applications on server start for a long
time now, using the _autodeploy_ directory. While acceptable in development
environments, the scanner used to deploy files in this directory is a security
risk for production and is therefore disabled in the `payaradomain` bundled with
Payara Server.

To reintroduce the capability of deploying an application on server startup
without the risk of enabling the deployment scanner, a feature from Payara Micro
was introduced: the ability to run asadmin commands at startup, either pre or
post boot.

To enable this feature, we have extended the `start-domain` feature to accept
two extra options: `--prebootcommandfile` and `--postbootcommandfile` which can
be used as follows:

*Pre-boot Commands*::
*Usage*: `asadmin> start-domain --prebootcommandfile=/path/to/file`
+
*Aim*: passing a list of commands as a file to the server to run pre-boot.
Due to the time during boot when the commands in this file are executed, this
only supports `set` commands.

*Post-boot Commands*::
*Usage*: `asadmin> start-domain --postbootcommandfile=/path/to/file`
+
*Aim*: passing a list of commands as a file to the server to run post-boot.
This is where commands such as service configuration commands should be run.

[NOTE]
====
There are some important caveats to note:

* Both files should be saved in a text format, with each command on it's own line.
* Lines where the first non-whitespace character is # are treated as comments
* Any blank lines will be ignored
* Any invalid or failing commands will be logged to the server.log and the file will continue to be processed
* The files *_must_* exist, and be accessible from Payara Server.
* Both pre-boot and post-boot files can be passed at the same time.
====
