= Arquillian Containers

:previewVersion: 5.181
include::partial$tech-preview.adoc[]

The Payara Arquillian containers provide various Arquillian containers for integration testing with Payara.

In version {currentVersion}, there are containers available for the following distributions:

* xref:documentation/ecosystem/arquillian-containers/payara-micro-managed.adoc[Payara Micro Managed]
* xref:documentation/ecosystem/arquillian-containers/payara-server-remote.adoc[Payara Server Remote]
* xref:documentation/ecosystem/arquillian-containers/payara-server-managed.adoc[Payara Server Managed]
* xref:documentation/ecosystem/arquillian-containers/payara-server-embedded.adoc[Payara Server Embedded]

=== Obtaining the Containers

Arquillian containers are included in a project via their Maven coordinates:

[source,XML]
----
<dependency>
    <groupId>fish.payara.arquillian</groupId>
    <artifactId>arquillian-payara-${container-name}</artifactId>
    <version>${version}</version>
</dependency>
----
