= Configuring REST monitoring

REST monitoring is configurable through asadmin commands. This feature is in
technical preview, so some things may not work quite as intended.

== Setting REST monitoring Configuration
The `set-payara-fang-configuration` asadmin command is used to configure
REST monitoring. This command requires the server to be running. Each
configuration property can be configured individually or all together.


=== Enabled

[source, shell]
----
asadmin> set-payara-fang-configuration --enabled=true
----
By default, REST monitoring is disabled.


=== Target

[source, shell]
----
asadmin> set-payara-fang-configuration --enabled=true --target=${Target}
----
If no target is specified, the command will enable REST monitoring on the
domain configuration _(server-config)_. The `--target` option enables
REST monitoring on another instance or cluster.


=== Context Root

[source, shell]
----
asadmin> set-payara-fang-configuration --contextroot=${ContextRoot}
----
The `contextroot` property defines which URLs the REST monitoring application
uses. The context root of the REST monitoring application defaults to `/fang`,
but can be specified with the `--contextroot` option.


=== Name

[source, shell]
----
asadmin> set-payara-fang-configuration --name=${Name}
----
The `name` property defines the name of the deployed REST monitoring
application. This option defaults to "Fang".


=== Security Enabled
[source, shell]
----
asadmin> set-payara-fang-configuration --securityenabled=true
----
The `securityenabled` property defines whether the REST monitoring application
is available over HTTPS. Since the REST monitoring application is hosted on the
`admin-listener`, this requires secure admin to be enabled.

Enabling secure admin can be done by first configuring the admin password with
the `change-admin-password` command, then using the `enable-secure-admin`
command. Enabling secure admin requires a server restart.

When `securityenabled` is set to true, a username and password is required to
use REST monitoring. By default the username and password is `fang`. The user is
defined in the `file` realm. The password can be changed with the
following command:
[source, shell]
----
asadmin> update-file-user --groups=fang --target=server-config --authrealmname=file fang
----
This updates the `fang` user, which is part of the `fang` group. Any users which
are able to login to the REST monitoring must be defined in the `file` realm and
be part of the `fang` group. You can create a new user with:
[source, shell]
----
asadmin> create-file-user --groups=fang --target=server-config --authrealmname=file whatever
----


== Getting REST monitoring Configuration
The `get-payara-fang-configuration` asadmin command is used to get the
configuration of the REST monitoring. This command requires the server to be
running.
