[[deploying-applications-from-the-command-line]]
= Deploying Applications From the Command Line

Payara Micro supports deploying applications directly from the command line.

[[deploying-an-application]]
== Deploying an Application

As noted in the section
link:/documentation/payara-micro/starting-instance.adoc#starting-an-instance-from-the-command-line[Starting an Instance],
all Payara Micro actions are run for the Payara Micro JAR, all in one command;
it is not possible to start an instance with one command, and deploy an application
to it with another.

The general structure of starting, configuring, and deploying an application to
an instance is as follows:

[source, shell]
----
java -jar payara-micro.jar --option1 --option2 ...
----

[[deploying-an-application-package]]
== Deploying an Application Package

To deploy a WAR file to an instance, you need to use the `--deploy` option, followed
by the path to the application to deploy. See below for an example of starting a
Payara Micro instance and deploying a WAR file:

[source, shell]
----
java -jar payara-micro.jar --deploy /home/user/example.war
----

NOTE: Since 4.1.2.181 and 5.181 the `--deploy` option is optional if your deployment file
ends with `.jar`, `.rar` or `.war` therefore the command line below can also be used
[source, shell]
----
java -jar payara-micro.jar /home/user/example.war
----

[[deploying-an-exploded-war]]
== Deploying an Exploded War

An exploded war can be deployed to a Payara Micro instance just be specifying
the path to the exploded war root directory on the `--deploy` command line or
via the API. The exploded war can be redeployed by creating a file _.reload_
in the root directory of the exploded war and updating its timestamp for example
using `touch .reload` in a LINUX machine.

[[deploying-multiple-applications]]
== Deploying Multiple Applications

If you want to deploy multiple applications to an instance with the `--deploy`
option, you must use it once for each application to be deployed; it does not
accept multiple paths.

For example, to deploy 2 applications:

[source, shell]
----
java -jar payara-micro.jar --deploy /home/user/example.war --deploy /home/user/test.war
----

Alternatively, you can use the `--deploymentDir` option. This option specifies
a directory to scan for deployable archives, allowing you to store all of the
applications you wish to be deployed in a directory, and have them be deployed
automatically upon instance startup.

[source, shell]
----
java -jar payara-micro.jar --deploymentDir /home/user/deployments
----

[[deploying-applications-from-a-maven-repository]]
== Deploying Applications from a Maven repository

You can deploy an application directly from a Maven repository using the
`--deployFromGAV` option. This option accepts a comma separated string denoting
a Maven artefact's _groupId_, _artifactId_, and _version_ attributes.

[source, shell]
----
java -jar payara-micro.jar --deployFromGAV "fish.payara.examples,test,1.0-SNAPSHOT"
----

This option can be used multiple times, and in conjunction with the standard
`--deploy` options.

By default, Payara Micro will only search for artefacts in the Maven Central
repository. If you wish to search additional repositories, you can add them to
the list of repositories to search with the `--additionalRepository` option:

[source, shell]
----
java -jar payara-micro.jar --deployFromGAV "fish.payara.examples,test,1.0-SNAPSHOT" --additionalRepository https://maven.java.net/content/repositories/promoted/
----

To search through multiple additional repositories, you can simply specify the
option multiple times:

[source, shell]
----
java -jar payara-micro.jar --deployFromGAV "fish.payara.examples,test,1.0-SNAPSHOT" --additionalRepository https://maven.java.net/content/repositories/promoted/ --additionalRepository https://raw.github.com/payara/Payara_PatchedProjects/master/
----
