= Asadmin Commands for Managing Password Aliases

=== `asadmin> create-password-alias`

*Usage:*
`asadmin> create-password-alias <alias-name>`

*Aim:*
Creates a new password alias using the provided name. The user is then
prompted to enter the associated password twice. Password Aliases can also be
created non-interactively using a password file.

[cols=",,,",options="headers"]
|====
|Option |Description |Default |Mandatory
|`--passwordfile`|The path to a password file.|Stored within the domain.xml|No
|====

*Example:*

Running the command will display output similar to the example below:

----
asadmin> create-password-alias example-alias-name
Enter the alias password>
Enter the alias password again>
Command create-password-alias executed successfully.
----

=== `asadmin> delete-password-alias`

*Usage:*
`asadmin> delete-password-alias <alias-name>`

*Aim:*
Deletes the specified password alias and password from the server.

*Example:*
Running the command will display output similar to the example below:

----
asadmin> delete-password-alias example-alias-name
Command delete-password-alias executed successfully.
----

=== `asadmin> list-password-aliases`

*Usage:*
`asadmin> list-password-aliases`

*Aim:*
Lists the password aliases for the domain.

*Example:*
Running the command  will display output similar to the example below:

----
asadmin> list-password-aliases
example-alias-name
another-example-alias
Command list-password-aliases executed successfully.
----

=== `asadmin> update-password-alias`

*Usage:*
`asadmin> update-password-alias <alias-name>`

*Aim:*
Updates the password associated with the given alias. Passwords can also be
updated non-interactively using a password file.

[cols=",,,",options="headers"]
|====
|Option |Description |Default |Mandatory
|`--passwordfile`|The path to a password file.|Stored within the domain.xml|No
|====

*Example:*

----
asadmin> update-password-alias example-alias-name
Enter the alias password>
Enter the alias password again>
Encrypted password for the alias example-alias-name updated successfully
Command update-password-alias executed successfully.
----
