= Timers in Deployment Groups

Timer facilities provided by EJB APIs `TimerService` and `@Scheduled` need special configuration in order to work intuitively for applications deployed to a deployment group.

There are four types of timers distinguished by their lifecycle (persistent, non-persistent) and the mean of their definition (declarative, programmatic).

Declarative timers are defined in EJB deployment descriptors or with annotation `@Scheduled`.
Programmatic timers are created via calls to `TimerService.create*Timer`.

== Non-Persistent Timers

Non-Persistent timers exist only in memory for duration in which the application runs of the instance.
Declarative non-persistent timers run on every instace, programmatic ones only on instance that created them.
When instance shuts down, the timer stops firing.
Instances do not see each others timers, calling `TimerService.getTimers()` only returns local non-persistent timers.

Non-Persistent timers have simpler lifecycle, but are not default.
`@Schedule` annotation needs attribute `persistent=false`, and `TimerConfig` objects also need to have their property `persistent` set to `false` explicitly.

== Peristent Timers

Persistent timers exist in persistent store for entire time for which application is deployed to a domain.
Contrary to non-persistent ones, each persistent timer is only executed on single instance of a deployment group.
When instance shuts down, timer migrates to another instance and continues firing there.
Persistent timers are therefore shared and `TimerService.getTimers()` returns all persistent timers, regardless of which instance created them.

Persistent timers are default kind of timers.

=== Preconditions for using Persistent Timers in Deployment Group

Because deployment groups do not need to share configurations amongst instances, there are several confiration and operational constraints that are not enforced by the server.
To achieve correct behavior of persistent timers within deployment group, following conditions need to be met:

* EJB Timer Service needs to use shared storage -- external database or DataGrid
* All instances of deployment group and Domain Administration Server share the same configuration of EJB Timer Service
* Applications with persistent timers are deployed to a deployment group and not managed on instance level afterwards
* Instances are members of only single deployment group


