[[payara-server-command-reference]]
= Payara Server Asadmin Commands

All Asadmin commands supported by _GlassFish Server 4 Open Source Edition_ are also supported by Payara Server. Some of the commands have been extended and new commands have been added which don't exist in GlassFish.

Here's a list of Payara Server Asadmin commands that are not supported by GlassFish or have been modified to accept additional parameters:

- link:/documentation/payara-server/admin-console/asadmin-recorder.adoc[Asadmin Recorder Commands]
- link:/documentation/payara-server/hazelcast/asadmin.adoc[Hazelcast Commands]
- link:/documentation/payara-server/health-check-service/asadmin-commands.adoc[Healthcheck Commands]
- link:/documentation/payara-server/jbatch/asadmin.adoc[JBatch Commands]
- link:/documentation/payara-server/jmx-monitoring-service/asadmin-commands.adoc[JMX Monitoring Commands]
- link:/documentation/microprofile/config.adoc[Microprofile Config Commands]
- link:/documentation/payara-server/notification-service/asadmin-commands.adoc[Notification Service Commands]
- link:/documentation/payara-server/phone-home/phone-home-asadmin.adoc[Phone Home Commands]
- link:/documentation/payara-server/request-tracing-service/asadmin-commands.adoc[Request Tracing Commands]
- link:/documentation/payara-server/rest-monitoring/configuring-rest-monitoring.adoc[REST Monitoring Commands]
- link:/documentation/payara-server/deployment-groups/asadmin-commands.adoc[Deployment Groups Commands]
- link:server-management-commands.adoc[Server Management Commands]
- link:misc-commands.adoc[Miscellaneous Commands]

== Command Autocompletion

_Since *5.184*&nbsp;_

When running the `asadmin` utility, command autocompletion is supported similar to that found in the bash linux utility. To use this, run `asadmin` without any arguments. Any commands entered from this prompt can be autocompleted by tapping the `<Tab>` key.

Alternatively, you can generate a bash autocompletion file to allow autocompletion without entering the `asadmin` prompt. To find out more, link:misc-commands.adoc#generate-bash-autocomplete-command[read the documentation here].
