= Ecosystem

The Payara Foundation not only provides application servers in the form of Payara
Server, Payara Micro, and Payara MicroProfile; there are also satellite projects
which complement and enhance the developer experience.

These include:

xref:documentation/ecosystem/maven-plugin.adoc[Payara Micro Maven Plugin]::
A plugin for Apache Maven is available for Payara Micro.

xref:documentation/ecosystem/netbeans-plugin.adoc[Payara NetBeans Plugin]::
A plugin for using Payara is available for NetBeans.

xref:documentation/ecosystem/cloud-connectors/cloud-connectors.adoc[Cloud Connectors]::
Cloud Connectors are a collection of JCA adapters which can interact with popular
message brokers, including:
* xref:documentation/ecosystem/cloud-connectors/amazon-sqs.adoc[Amazon SQS]
* xref:documentation/ecosystem/cloud-connectors/apache-kafka.adoc[Apache Kafka]
* xref:documentation/ecosystem/cloud-connectors/azure-sb.adoc[Azure Service Bus]
* xref:documentation/ecosystem/cloud-connectors/mqtt.adoc[MQTT]
